# Registered email : akibhasan011@gmail.com

In [6]:
# You must run this code and use this dataset for all questions

import numpy as np
import pandas as pd

np.random.seed(24)

num_employees = 50  # you can increase this if needed

# Employee data
emp_ids = np.arange(101, 101 + num_employees)
emp_ages = np.random.randint(20, 55, num_employees)
emp_income = np.random.randint(35000, 95000, num_employees)

# Fixed set of roles (repetition allowed)
roles_list = [
    "HR Manager",
    "Software Developer",
    "Accountant",
    "Marketing Executive",
    "Sales Executive",
    "Backend Developer",
    "HR Executive",
    "Financial Analyst",
    "Digital Marketer",
    "Operations Manager"
]

emp_roles = np.random.choice(roles_list, num_employees)

# Create DataFrame
data = pd.DataFrame({
    "emp_id": emp_ids,
    "emp_age": emp_ages,
    "emp_salary": emp_income,
    "role": emp_roles
})

# Save dataset
data.to_csv("staff_data.csv", index=False)

# 1) NumPy — 5 Questions

Q1.
Use  NumPy arrays from the emp_ages and emp_salary columns.

 Print both arrays and display:

data type

number of dimensions

shape

total number of elements

In [ ]:
# print(data)

ages = np.array(data['emp_age'])
salaries = np.array(data['emp_salary'])

# for age
print(ages)
print(ages.dtype)
print(ages.ndim)
print(ages.shape)
print(ages.size)

# for salaries
print(salaries)
print(salaries.dtype)
print(salaries.ndim)
print(salaries.shape)
print(salaries.size)

[54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]
int64
1
(50,)
50
[51725 38495 35452 82295 72187 58915 76159 92864 76155 90494 68641 48079
 56879 83682 94722 91041 48899 68744 63187 74146 75641 47678 76760 78354
 60584 79898 59682 71888 51086 73700 82550 71447 76100 72269 73314 87428
 94427 84188 52013 63326 44396 59500 55523 58602 90794 41061 82331 73048
 59727 50398]
int64
1
(50,)
50

Q2.
Using NumPy functions:
Find the maximum and minimum salary

Calculate the average salary

Calculate the average age

 Print all results.

In [ ]:
# print(salaries)
# print(ages)

[54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]

In [ ]:
max_salary = np.max(salaries)
print(f"Maximum salary : {max_salary}")

min_salary = np.min(salaries)
print(f"Minimum salary : {min_salary}")

avg_salary = np.average(salaries)
print(f"Avg salary : {avg_salary}")

avg_age = np.average(ages)
print(f"Avg age : {avg_age}")

Maximum salary : 94722
Minimum salary : 35452
Avg salary : 68409.48
Avg age : 35.44

Q3.
From the emp_ages array:

Extract employees who:

are aged between 25 and 40,
 AND

Emp_salary : have salary greater than 50,000

Then :

Print the filtered values

Count how many employees satisfy this condition

In [ ]:
ages = np.array(data['emp_age'])
salaries = np.array(data['emp_salary'])

In [ ]:
new_age = (ages >= 25) & (ages <= 40)
# print(new_age)

salary = salaries > 50000
# print(salary)

combined = new_age & salary

print(ages[combined])
print(salaries[combined])

cnt = np.sum(combined)
print(cnt)

[37 37 35 38 31 29 38 27 32 26 37 26 30 30 27 25 31]
[72187 58915 92864 90494 68641 56879 83682 94722 74146 78354 79898 59682
 73700 84188 52013 63326 59727]
17

Q4.
Create a new NumPy array where each employee’s age is adjusted based on:

Add 4 years if age is less than the average age

Add 2 years if age is greater than or equal to the average age

Do NOT modify the original array.

Print:

original array

updated array

average age used for condition

In [ ]:
# print(ages)
# print(salaries)

In [ ]:
avg_age = np.average(ages)
# print(avg_age)

new_age = np.where( ages < avg_age, ages + 4, ages + 2 )
# print(new_age)

print(f"Orginal array : {ages}")
print(f"Avg age : {avg_age}")
print(f"Updated array : {new_age}")

Orginal array : [54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]
Avg age : 35.44
Updated array : [56 27 24 45 39 39 25 39 28 40 35 39 33 40 31 47 53 50 24 36 53 55 25 30
 55 39 30 25 47 34 24 49 55 55 27 28 25 34 31 29 41 24 49 43 26 54 44 56
 35 52]

Q5.

Using NumPy:

Assume all salaries of Tech roles increase by 8%

Calculate the new total salary expense

Find the overall increase in expense after the raise

Print both old and new totals along with the difference.

In [ ]:
tech = (data["role"] == "Backend Developer") | (data["role"] == "Software Developer") | (data["role"] == "Digital Marketer")

# print(salaries)

updated_salary = np.where(tech, salaries * (1 + 8/100), salaries)

# print(updated_salary)
# print(updated_salary.size)

old = np.sum(salaries)
# print(old)

new = np.sum(updated_salary)
# print(new)

difference = new - old
# print(difference)

print(f"Sum of old salary : {old}")
print(f"Sum of new salary : {new}")
print(f"Difference : {difference}")

Sum of old salary : 3420474
Sum of new salary : 3524808.08
Difference : 104334.08000000007

# 2) Pandas — 5 Questions

Q6.

Load the staff_data.csv file into a Pandas DataFrame.

Display the first 3 rows

Show dataset information using .info()

Display summary statistics using .describe()

In [17]:
df = pd.read_csv('staff_data.csv')
print(df.head(3))
df.info()
df.describe()

   emp_id  emp_age  emp_salary                role
0     101       54       51725          HR Manager
1     102       23       38495          Accountant
2     103       20       35452  Operations Manager
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      50 non-null     int64
 1   emp_age     50 non-null     int64
 2   emp_salary  50 non-null     int64
 3   role        50 non-null     object
dtypes: int64(3), object(1)
memory usage: 1.7+ KB

          emp_id    emp_age    emp_salary
count   50.00000  50.000000     50.000000
mean   125.50000  35.440000  68409.480000
std     14.57738  11.768446  15727.122334
min    101.00000  20.000000  35452.000000
25%    113.25000  24.250000  57309.750000
50%    125.50000  35.000000  72037.500000
75%    137.75000  46.500000  79512.000000
max    150.00000  54.000000  94722.000000

Q7.
Filter the dataset to include only:

emp_id, emp_age, role

Then:

Select employees whose age is between 25 and 40

Sort them by emp_id

Display the last 3 rows of the result

In [9]:
# df.head()

In [18]:
new_df = df.loc[:, ['emp_id', 'emp_age', 'role']]
new = (new_df['emp_age'] >= 25) & (new_df['emp_age'] <= 40)

new_df = new_df[new]
# print(new_df)

new_df = new_df.sort_values('emp_id').tail(3)

print(new_df)

    emp_id  emp_age                 role
39     140       25      Sales Executive
40     141       39  Marketing Executive
48     149       31     Digital Marketer

Q8.

Filter the DataFrame to show only employees working in the "HR" role.

Print the filtered data

Show the total number of HR employees

In [11]:
new_df = df[ (df['role'] == "HR Manager") | (df['role'] == "HR Executive") ]
print(new_df)
print(f"Total HR employee : {len(new_df)}")

    emp_id  emp_age  emp_salary          role
0      101       54       51725    HR Manager
5      106       37       58915    HR Manager
9      110       38       90494  HR Executive
24     125       53       60584  HR Executive
27     128       21       71888  HR Executive
38     139       27       52013    HR Manager
42     143       47       55523  HR Executive
44     145       22       90794  HR Executive
45     146       52       41061    HR Manager
Total HR employee : 9

Q9.

Sort the DataFrame by:

emp_age (ascending)

and then by emp_salary (descending)

Display the top 5 employees after sorting, including:

emp_id

role

emp_salary

In [12]:
df.head()

   emp_id  emp_age  emp_salary                role
0     101       54       51725          HR Manager
1     102       23       38495          Accountant
2     103       20       35452  Operations Manager
3     104       43       82295    Digital Marketer
4     105       37       72187   Backend Developer

In [24]:
new_df = df.sort_values(["emp_age", "emp_salary"], ascending = [1, 0])
# new_df

new_df = df.loc[:,['emp_id','role', 'emp_salary']]
new_df.head()

   emp_id                role  emp_salary
0     101          HR Manager       51725
1     102          Accountant       38495
2     103  Operations Manager       35452
3     104    Digital Marketer       82295
4     105   Backend Developer       72187

Q10.

Using .loc:

Increase salary by 12% for "Software Developer" and "Backend Developer"

Increase salary by 5% for all other roles

Then:

Print the dataframe that includes role , previous_salary , new_salary , increase_of_salary

In [25]:
# df.head()

In [15]:
new_df = df

In [30]:
df_eng = new_df.loc[(new_df['role'] == "Software Developer") | (new_df['role'] == "Backend Developer")]


df_eng["previous_salary"] = df_eng["emp_salary"]

df_eng["new_salary"] = df_eng["emp_salary"] * (1 + 12/100)

df_eng["increase_of_salary"] = df_eng["new_salary"] - df_eng["previous_salary"]

# print(df_eng)

df_not_eng = new_df.loc[(new_df['role'] != "Software Developer") & (new_df['role'] != "Backend Developer")]

df_not_eng["previous_salary"] = df_not_eng["emp_salary"]

df_not_eng["new_salary"] = df_not_eng["emp_salary"] * (1 + 5/100)

df_not_eng["increase_of_salary"] = df_not_eng["new_salary"] - df_not_eng["previous_salary"]

# print(df_not_eng)

/tmp/ipykernel_7912/3820233710.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_eng["previous_salary"] = df_eng["emp_salary"]
/tmp/ipykernel_7912/3820233710.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_eng["new_salary"] = df_eng["emp_salary"] * (1 + 12/100)
/tmp/ipykernel_7912/3820233710.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_eng["increase_of_salary"] = df_eng["new_salary"] - df_eng["previous_salary"]
/tmp/ipykernel_7912/3820233710.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_eng["previous_salary"] = df_not_eng["emp_salary"]
/tmp/ipykernel_7912/3820233710.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_eng["new_salary"] = df_not_eng["emp_salary"] * (1 + 5/100)
/tmp/ipykernel_7912/3820233710.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_eng["increase_of_salary"] = df_not_eng["new_salary"] - df_not_eng["previous_salary"]