In [4]:
print("In the name of Allah")

In the name of Allah

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("student_data.csv")

In [7]:
print(df)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [8]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [9]:
student_id = df['StudentID']

# print(student_id)

print(type(student_id))

<class 'pandas.core.series.Series'>

## Different File Loading in Pandas

In [10]:
# csv file

csv_data = pd.read_csv('student_data.csv')

print(csv_data)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [11]:
print(type(csv_data))

<class 'pandas.core.frame.DataFrame'>

In [12]:
# excel file

excel_file = pd.read_excel("phitron_student_marks.xlsx")

print(excel_file)
print(type(excel_file))

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka
<class 'pandas.core.frame.DataFrame'>

In [13]:
# parquet file

parquet_file = pd.read_parquet("students.parquet")

print(parquet_file)
print(type(parquet_file))

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka
<class 'pandas.core.frame.DataFrame'>

In [14]:
# json file

json_file = pd.read_json("data.json")

print(json_file)
print(type(json_file))

  StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0    PH1001       Alif Rahman                    85               85
1    PH1002     Fatima Akhter                    92               92
2    PH1004  Jannatul Ferdous                    78               78

   Python Marks
0            88
1            90
2            82
<class 'pandas.core.frame.DataFrame'>

In [16]:
df = pd.read_csv("student_data.csv")

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [17]:
# first er kichu value

df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

In [19]:
df.head(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka

In [20]:
# last er kichu valueabs

df.tail()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [21]:

df.tail(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [23]:
# column

df.columns

Index(['StudentID', 'FullName', 'Data Structure Marks', 'Algorithm Marks',
       'Python Marks', 'CompletionStatus', 'EnrollmentDate', 'Instructor',
       'Location'],
      dtype='object')

In [28]:
import numpy as np

col = np.array(df.columns)
print(col)
print(col.dtype)

['StudentID' 'FullName' 'Data Structure Marks' 'Algorithm Marks'
 'Python Marks' 'CompletionStatus' 'EnrollmentDate' 'Instructor'
 'Location']
object

In [33]:
# index
df.index

idx = np.array(df.index)
print(idx)
print(idx.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
int64

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudentID             20 non-null     object
 1   FullName              20 non-null     object
 2   Data Structure Marks  16 non-null     float64
 3   Algorithm Marks       16 non-null     float64
 4   Python Marks          15 non-null     float64
 5   CompletionStatus      20 non-null     object
 6   EnrollmentDate        20 non-null     object
 7   Instructor            20 non-null     object
 8   Location              20 non-null     object
dtypes: float64(3), object(6)
memory usage: 1.5+ KB

In [36]:
df.sample(10)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka

In [41]:
df.sample(10)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram

In [43]:
# statistical values

df.describe()

       Data Structure Marks  Algorithm Marks  Python Marks
count             16.000000        16.000000     15.000000
mean              84.000000        84.000000     85.666667
std                6.501282         6.501282      5.394000
min               72.000000        72.000000     76.000000
25%               79.500000        79.500000     83.000000
50%               85.500000        85.500000     85.000000
75%               88.250000        88.250000     88.500000
max               94.000000        94.000000     95.000000

## Transforming to df from inbuilt datas

In [56]:
my_list = [['Alice', 25], ['Bob', 30], ['Charlie', 28]]

list_df = pd.DataFrame(my_list, columns = ['Name', 'Age'], index = [1, 2, 3]) 

print(type(list_df))
list_df

<class 'pandas.core.frame.DataFrame'>

      Name  Age
1    Alice   25
2      Bob   30
3  Charlie   28

In [62]:
my_tuple = (('Alice', 25), ('Bob', 30), ('Charlie', 28))

tuple_df = pd.DataFrame(my_tuple, columns = ['Name', 'Age'])

print(type(tuple_df))
tuple_df

<class 'pandas.core.frame.DataFrame'>

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   28

In [63]:
my_dict = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 29,28]
}

dict_df = pd.DataFrame(my_dict)

dict_df

      Name  Age
0    Alice   25
1      Bob   29
2  Charlie   28

In [65]:
my_data = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'Paris'},
    {'Name': 'Charlie', 'Age': 28}
]

data_df = pd.DataFrame(my_data)

data_df

      Name  Age      City
0    Alice   25  New York
1      Bob   30     Paris
2  Charlie   28       NaN

## Accessing values from DF

In [66]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [68]:
# accessing a column

df['FullName']

type(df["FullName"])

pandas.core.series.Series

In [86]:
# df.loc[ind start : ind end, col_start : col_end]

df.loc[0]

type(df.loc[0])

pandas.core.series.Series

In [87]:
# multiple row( normal list )

df.loc[[2, 3, 19]]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [88]:
# multiple row( range )

df.loc[3:7]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram

In [89]:
# single column

df.loc[:,['Python Marks']]

    Python Marks
0           88.0
1            NaN
2           85.0
3           82.0
4           95.0
5           78.0
6            NaN
7           85.0
8           76.0
9           88.0
10          91.0
11          87.0
12          79.0
13           NaN
14          84.0
15           NaN
16          93.0
17          85.0
18           NaN
19          89.0

In [90]:
# multiple column

df.loc[:, ['Python Marks', 'Algorithm Marks']]

    Python Marks  Algorithm Marks
0           88.0             85.0
1            NaN             92.0
2           85.0             88.0
3           82.0             78.0
4           95.0              NaN
5           78.0             75.0
6            NaN             80.0
7           85.0             81.0
8           76.0             72.0
9           88.0             89.0
10          91.0              NaN
11          87.0             85.0
12          79.0             75.0
13           NaN              NaN
14          84.0             86.0
15           NaN             94.0
16          93.0             90.0
17          85.0             88.0
18           NaN              NaN
19          89.0             86.0

In [91]:
type(df.loc[:, ['Python Marks', 'Algorithm Marks']])

pandas.core.frame.DataFrame

In [92]:
# row with columns

df.loc[3:7, 'CompletionStatus']

3      Completed
4    In Progress
5      Completed
6    In Progress
7      Completed
Name: CompletionStatus, dtype: object

## Changing index and columns and iloc

In [93]:
df_index = df.set_index('StudentID')

In [94]:
df_index

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [95]:
df_index.iloc[3:7]

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka

In [98]:
df_index.iloc[:,0:4]

,FullName,Data Structure Marks,Algorithm Marks,Python Marks
StudentID,,,,
PH1001,Alif Rahman,85.0,85.0,88.0
PH1002,Fatima Akhter,92.0,92.0,NaN
PH1003,Imran Hossain,88.0,88.0,85.0
PH1004,Jannatul Ferdous,78.0,78.0,82.0
PH1005,Kamal Uddin,NaN,NaN,95.0
PH1006,Laila Begum,75.0,75.0,78.0
PH1007,Mahmudul Hasan,80.0,80.0,NaN
PH1008,Nadia Islam,81.0,81.0,85.0
PH1009,Omar Faruq,72.0,72.0,76.0
PH1010,Priya Sharma,89.0,89.0,88.0
PH1011,Rahim Sheikh,NaN,NaN,91.0
PH1012,Sadia Chowdhury,85.0,85.0,87.0
PH1013,Tanvir Ahmed,75.0,75.0,79.0
PH1014,Urmi Akter,NaN,NaN,NaN
PH1015,Wahiduzzaman,86.0,86.0,84.0
PH1016,Ziaur Rahman,94.0,94.0,NaN
PH1017,Afsana Mimi,90.0,90.0,93.0
PH1018,Babul Ahmed,88.0,88.0,85.0
PH1019,Faria Rahman,NaN,NaN,NaN
PH1020,Nasir Khan,86.0,86.0,89.0

In [103]:
df.rename(columns = {'FullName' : 'Full Name', 'Algorithm Marks' : 'Algo Marks'}, inplace = True)

df

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

## Changing values and Iteration

In [106]:
# row delete
df.drop(0, inplace = True)

In [107]:
df

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [108]:
# column deletion

df.drop('Instructor', axis = 1, inplace = True)
df

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [117]:
df.loc[1, 'Python Marks'] = 90
df.loc[1, 'CompletionStatus'] = 'Completed'
df.head()

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location,Python Marks\t
1,PH1002,Fatima Akhter,92.0,92.0,90.0,Completed,2024-01-20,Chattogram,90.0
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Dhaka,NaN
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Sylhet,NaN
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi,NaN

In [119]:
df.loc[1:3, 'Python Marks'] += 2

df.head()

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location,Python Marks\t
1,PH1002,Fatima Akhter,92.0,92.0,92.0,Completed,2024-01-20,Chattogram,90.0
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10,Dhaka,NaN
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12,Sylhet,NaN
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi,NaN

In [122]:
for i,series in df.iterrows() :
    print(f"{i} : {series}")

TypeError: DataFrame.iterrows() got an unexpected keyword argument 'index'

In [123]:
for i in df.itertuples(index = False) :
    print(i)

Pandas(StudentID='PH1002', _1='Fatima Akhter', _2=92.0, _3=92.0, _4=92.0, CompletionStatus='Completed', EnrollmentDate='2024-01-20', Location='Chattogram', _8=90.0)
Pandas(StudentID='PH1003', _1='Imran Hossain', _2=88.0, _3=88.0, _4=87.0, CompletionStatus='Completed', EnrollmentDate='2024-02-10', Location='Dhaka', _8=nan)
Pandas(StudentID='PH1004', _1='Jannatul Ferdous', _2=78.0, _3=78.0, _4=84.0, CompletionStatus='Completed', EnrollmentDate='2024-02-12', Location='Sylhet', _8=nan)
Pandas(StudentID='PH1005', _1='Kamal Uddin', _2=nan, _3=nan, _4=95.0, CompletionStatus='In Progress', EnrollmentDate='2024-03-05', Location='Chattogram', _8=nan)
Pandas(StudentID='PH1006', _1='Laila Begum', _2=75.0, _3=75.0, _4=78.0, CompletionStatus='Completed', EnrollmentDate='2024-03-08', Location='Rajshahi', _8=nan)
Pandas(StudentID='PH1007', _1='Mahmudul Hasan', _2=80.0, _3=80.0, _4=nan, CompletionStatus='In Progress', EnrollmentDate='2024-04-01', Location='Dhaka', _8=nan)
Pandas(StudentID='PH1008', _1='Nadia Islam', _2=81.0, _3=81.0, _4=85.0, CompletionStatus='Completed', EnrollmentDate='2024-04-22', Location='Chattogram', _8=nan)
Pandas(StudentID='PH1009', _1='Omar Faruq', _2=72.0, _3=72.0, _4=76.0, CompletionStatus='Completed', EnrollmentDate='2024-05-16', Location='Dhaka', _8=nan)
Pandas(StudentID='PH1010', _1='Priya Sharma', _2=89.0, _3=89.0, _4=88.0, CompletionStatus='Completed', EnrollmentDate='2024-05-20', Location='Sylhet', _8=nan)
Pandas(StudentID='PH1011', _1='Rahim Sheikh', _2=nan, _3=nan, _4=91.0, CompletionStatus='In Progress', EnrollmentDate='2024-06-11', Location='Khulna', _8=nan)
Pandas(StudentID='PH1012', _1='Sadia Chowdhury', _2=85.0, _3=85.0, _4=87.0, CompletionStatus='Completed', EnrollmentDate='2024-06-14', Location='Chattogram', _8=nan)
Pandas(StudentID='PH1013', _1='Tanvir Ahmed', _2=75.0, _3=75.0, _4=79.0, CompletionStatus='Completed', EnrollmentDate='2024-07-02', Location='Dhaka', _8=nan)
Pandas(StudentID='PH1014', _1='Urmi Akter', _2=nan, _3=nan, _4=nan, CompletionStatus='Not Started', EnrollmentDate='2024-07-09', Location='Rajshahi', _8=nan)
Pandas(StudentID='PH1015', _1='Wahiduzzaman', _2=86.0, _3=86.0, _4=84.0, CompletionStatus='Completed', EnrollmentDate='2024-08-18', Location='Dhaka', _8=nan)
Pandas(StudentID='PH1016', _1='Ziaur Rahman', _2=94.0, _3=94.0, _4=nan, CompletionStatus='In Progress', EnrollmentDate='2024-08-21', Location='Chattogram', _8=nan)
Pandas(StudentID='PH1017', _1='Afsana Mimi', _2=90.0, _3=90.0, _4=93.0, CompletionStatus='Completed', EnrollmentDate='2025-09-01', Location='Dhaka', _8=nan)
Pandas(StudentID='PH1018', _1='Babul Ahmed', _2=88.0, _3=88.0, _4=85.0, CompletionStatus='Completed', EnrollmentDate='2025-09-05', Location='Sylhet', _8=nan)
Pandas(StudentID='PH1019', _1='Faria Rahman', _2=nan, _3=nan, _4=nan, CompletionStatus='Not Started', EnrollmentDate='2025-09-15', Location='Chattogram', _8=nan)
Pandas(StudentID='PH1020', _1='Nasir Khan', _2=86.0, _3=86.0, _4=89.0, CompletionStatus='Completed', EnrollmentDate='2025-10-02', Location='Dhaka', _8=nan)

## Sorting

In [124]:
df

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location,Python Marks\t
1,PH1002,Fatima Akhter,92.0,92.0,92.0,Completed,2024-01-20,Chattogram,90.0
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10,Dhaka,NaN
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12,Sylhet,NaN
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi,NaN
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram,NaN
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka,NaN
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet,NaN
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram,NaN
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka,NaN
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka,NaN
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka,NaN
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet,NaN
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka,NaN

In [131]:
copy = df.sort_values('Data Structure Marks')
copy

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location,Python Marks\t
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi,NaN
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka,NaN
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12,Sylhet,NaN
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka,NaN
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet,NaN
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10,Dhaka,NaN
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka,NaN
1,PH1002,Fatima Akhter,92.0,92.0,92.0,Completed,2024-01-20,Chattogram,90.0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram,NaN
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram,NaN
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna,NaN
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi,NaN
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram,NaN

In [132]:
copy = df.sort_values('Data Structure Marks', ascending = False)
copy

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location,Python Marks\t
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram,NaN
1,PH1002,Fatima Akhter,92.0,92.0,92.0,Completed,2024-01-20,Chattogram,90.0
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka,NaN
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet,NaN
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet,NaN
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10,Dhaka,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram,NaN
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka,NaN
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12,Sylhet,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi,NaN
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka,NaN
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka,NaN
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram,NaN
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna,NaN
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi,NaN
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram,NaN

In [133]:
copy = df.sort_values(['Data Structure Marks','Algo Marks'], ascending = False)
copy

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location,Python Marks\t
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram,NaN
1,PH1002,Fatima Akhter,92.0,92.0,92.0,Completed,2024-01-20,Chattogram,90.0
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka,NaN
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet,NaN
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet,NaN
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10,Dhaka,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram,NaN
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka,NaN
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12,Sylhet,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi,NaN
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka,NaN
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka,NaN
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram,NaN
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna,NaN
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi,NaN
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram,NaN

In [135]:
copy = df.sort_values(['Data Structure Marks','Algo Marks', 'Python Marks'], ascending = False)
copy

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location,Python Marks\t
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram,NaN
1,PH1002,Fatima Akhter,92.0,92.0,92.0,Completed,2024-01-20,Chattogram,90.0
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka,NaN
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet,NaN
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10,Dhaka,NaN
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram,NaN
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka,NaN
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12,Sylhet,NaN
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi,NaN
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka,NaN
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram,NaN
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna,NaN
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi,NaN
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram,NaN

In [139]:
copy = df.sort_values(['Data Structure Marks', 'Python Marks'], ascending = [0, 1])
# 0 means desceding, 1 means ascending
copy

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location,Python Marks\t
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram,NaN
1,PH1002,Fatima Akhter,92.0,92.0,92.0,Completed,2024-01-20,Chattogram,90.0
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka,NaN
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet,NaN
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet,NaN
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10,Dhaka,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram,NaN
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka,NaN
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12,Sylhet,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi,NaN
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka,NaN
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka,NaN
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna,NaN
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram,NaN
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi,NaN
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram,NaN

## Filtering data based on condition

In [140]:
df

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location,Python Marks\t
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi,NaN
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka,NaN
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12,Sylhet,NaN
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka,NaN
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet,NaN
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10,Dhaka,NaN
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka,NaN
1,PH1002,Fatima Akhter,92.0,92.0,92.0,Completed,2024-01-20,Chattogram,90.0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram,NaN
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram,NaN
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna,NaN
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi,NaN
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram,NaN

In [142]:
not_started = df.loc[df['CompletionStatus'] == 'Not Started']
not_started

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location,Python Marks\t
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi,NaN
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram,NaN

In [145]:
completed = df.loc[df['CompletionStatus'] == 'Completed']
completed

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location,Python Marks\t
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi,NaN
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka,NaN
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12,Sylhet,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka,NaN
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet,NaN
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10,Dhaka,NaN
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka,NaN
1,PH1002,Fatima Akhter,92.0,92.0,92.0,Completed,2024-01-20,Chattogram,90.0

In [146]:
# completed and ds marks is greater or equal 90

completed_ds90 = df.loc[(df['CompletionStatus'] == 'Completed') & (df['Data Structure Marks']  >= 90)] 

completed_ds90

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location,Python Marks\t
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka,NaN
1,PH1002,Fatima Akhter,92.0,92.0,92.0,Completed,2024-01-20,Chattogram,90.0