In [1]:
print("In the name of Allah")

In the name of Allah

1. Create a Pandas Series from the list [10, 20, 30, 40, 50]. Print the Series, its index, and data type. Then create a DataFrame with columns "Name", "Age", and "City" containing at least 4 rows of data.

In [2]:
import pandas as pd

In [6]:
data = [10, 20, 30, 40, 50]
s = pd.Series(data)
print(s)
print(s.index)
print(s.dtype)

0    10
1    20
2    30
3    40
4    50
dtype: int64
RangeIndex(start=0, stop=5, step=1)
int64

In [8]:
data = {
    "Name": ["Akib", "Rahim", "Karim", "Sakib"],
    "Age": [22, 23, 21, 24],
    "City": ["Dhaka", "Sylhet", "Chittagong", "Khulna"]
}

dataframe = pd.DataFrame(data)
dataframe

    Name  Age        City
0   Akib   22       Dhaka
1  Rahim   23      Sylhet
2  Karim   21  Chittagong
3  Sakib   24      Khulna

2. Using any DataFrame, write code to print the number of rows and columns, column data types (.dtypes), and summary statistics (.describe()).

In [16]:
data = {
    "Name": ["Akib", "Rahim", "Karim", "Sakib"],
    "Age": [22, 23, 21, 24],
    "City": ["Dhaka", "Sylhet", "Chittagong", "Khulna"]
}

df = pd.DataFrame(data)
# df

print(df.shape)
print(df.dtypes)

(4, 3)
Name    object
Age      int64
City    object
dtype: object

In [18]:
print(df.describe)

<bound method NDFrame.describe of     Name  Age        City
0   Akib   22       Dhaka
1  Rahim   23      Sylhet
2  Karim   21  Chittagong
3  Sakib   24      Khulna>

3. Create a DataFrame using the dictionary below:


data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}

Print .columns, .index. Access a single column and one full row.

In [55]:
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}

df = pd.DataFrame(data)

df

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [56]:
print(df.columns)
print(df.index)

Index(['Product', 'Price', 'Quantity'], dtype='object')
RangeIndex(start=0, stop=4, step=1)

In [57]:
print(df['Product'])

0       Pen
1      Book
2    Eraser
3    Pencil
Name: Product, dtype: object

In [58]:
df.loc[1]

Product     Book
Price         50
Quantity      60
Name: 1, dtype: object

4. Using .loc[] and .iloc[], show the first row, the second column, and a 2×2 block    from the middle of your DataFrame.

In [59]:
df

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [60]:
print(df.loc[0])

print(df.iloc[0])

Product     Pen
Price        10
Quantity    100
Name: 0, dtype: object
Product     Pen
Price        10
Quantity    100
Name: 0, dtype: object

In [61]:
print(df.loc[:,'Price'])

0    10
1    50
2     5
3     7
Name: Price, dtype: int64

In [62]:
print(df.iloc[:, 1])

0    10
1    50
2     5
3     7
Name: Price, dtype: int64

In [63]:
print(df.loc[1:2, ['Price','Quantity']])

   Price  Quantity
1     50        60
2      5       200

In [64]:
print(df.iloc[1:3, 1:3])

   Price  Quantity
1     50        60
2      5       200

5. Create a 4×3 DataFrame of student names and marks. Drop one column using .drop(), drop one row by index

In [86]:
data = {
    "Name": ["Akib", "Rahim", "Karim", "Sakib"],
    "Math": [85, 78, 92, 88],
    "Physics": [80, 75, 90, 85]
}

df = pd.DataFrame(data)

In [87]:
df

    Name  Math  Physics
0   Akib    85       80
1  Rahim    78       75
2  Karim    92       90
3  Sakib    88       85

In [88]:
df.drop('Physics', axis = 1, inplace = True)

In [89]:
df

    Name  Math
0   Akib    85
1  Rahim    78
2  Karim    92
3  Sakib    88

In [90]:
df.drop(1, axis = 0, inplace = True)

In [91]:
df

    Name  Math
0   Akib    85
2  Karim    92
3  Sakib    88

6. Create a DataFrame of employees with columns "Name", "Department", and "Salary". Sort it by "Salary" in ascending order and by "Name" in descending order.

In [92]:
data = {
    "Name": ["Akib", "Rahim", "Karim", "Sakib"],
    "Department": ["IT", "HR", "Finance", "Marketing"],
    "Salary": [50000, 45000, 55000, 48000]
}

df = pd.DataFrame(data)
df

    Name Department  Salary
0   Akib         IT   50000
1  Rahim         HR   45000
2  Karim    Finance   55000
3  Sakib  Marketing   48000

In [97]:
copy = df.sort_values(["Salary", "Name"], ascending = [1, 0])

In [98]:
copy

    Name Department  Salary
1  Rahim         HR   45000
3  Sakib  Marketing   48000
0   Akib         IT   50000
2  Karim    Finance   55000

7. Create a DataFrame of 8 students with columns "Name" and "Score". Filter and print students with Score > 60 and those with Score < 40.

In [107]:
data = {
    "Name": ["Akib", "Rahim", "Karim", "Sakib", "Naim", "Jahid", "Rafi", "Tanvir"],
    "Score": [85, 78, 92, 88, 76, 81, 90, 30]
}

df = pd.DataFrame(data)
df

     Name  Score
0    Akib     85
1   Rahim     78
2   Karim     92
3   Sakib     88
4    Naim     76
5   Jahid     81
6    Rafi     90
7  Tanvir     30

In [108]:
df_greater_60 = df.loc[(df['Score'] > 60)]
df_greater_60

    Name  Score
0   Akib     85
1  Rahim     78
2  Karim     92
3  Sakib     88
4   Naim     76
5  Jahid     81
6   Rafi     90

In [109]:
df_less_than_40 = df.loc[df['Score'] < 40]
df_less_than_40

     Name  Score
7  Tanvir     30